- host: balancer
  os: 'centos/7'           # This value you can get from "vagrant box" command
  ip: '192.168.33.100'
  memory: '512'
  cpu_num: '1'
  script:
     - yum install -y nano

- host: tomcat1
  os: 'centos/7'
  ip: '192.168.33.110'
  memory: '512'
  cpu_num: '1'
  script:
    - yum install -y nano

- host: tomcat2
  os: 'centos7'
  ip: '192.168.33.120'
  memory: '512'
  cpu_num: '1'
  script:
    - yum install -y nano

#- host: centos6-host
#  os: 'centos6'
#  ip: '192.168.33.130'
#  memory: '512'
#  cpu_num: '1'
#  script:
#   - yum install -y nano





